{% set name = "dace" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dace-{{ version }}.tar.gz
  sha256: 7c8280d84b747b36609c557527d8f42a8d955275492e15af20dea7ec1918c4a6

build:
  entry_points:
    - dacelab = dace.cli.dacelab:main
    - sdfv = dace.cli.sdfv:main
    - sdfgcc = dace.cli.sdfgcc:main
    - sdprof = dace.cli.sdprof:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
    - cmake >=3.18
  run:
    - python
    - aenum >=3.1
    - astunparse
    - chardet >=3.0.4
    - cmake >=3.18
    - dill
    - flask
    - networkx >=2.5
    - numpy
    - ply
    - pyyaml
    - requests
    - sympy >=1.9
    - websockets
    - pyreadline  # [win]
    - dataclasses  # [py<37]
    - typing-compat  # [py<38]

test:
  imports:
    - dace
  commands:
    - sdfgcc --help
    - dacelab --help
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spcl/dace
  summary: Data-Centric Parallel Programming Framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tbennun
    - lukastruemper
