{% set name = "dace" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dace-{{ version }}.tar.gz
  sha256: 13e5c5af31ca7313839dee257305d2020ac79c3cfa77af8ea3feb5260b0582a4

build:
  entry_points:
    - dacelab = dace.cli.dacelab:main
    - sdfv = dace.cli.sdfv:main
    - sdfgcc = dace.cli.sdfgcc:main
    - sdprof = dace.cli.sdprof:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python
    - pip
    - cmake >=3.18
  run:
    - python
    - aenum >=3.1
    - astunparse >=1.6.3
    - chardet >=3.0.4
    - click >=7.1.2
    - cmake >=3.18
    - decorator >=4.4.2
    - distro >=1.5.0
    - flask >=2.3.2
    - idna >=2.10
    - itsdangerous >=2.0.0
    - jinja2 >=3.0.0
    - markupsafe >=2.0.0
    - mpmath >=1.1.0
    - networkx >=2.5
    - numpy >=1.21
    - packaging >=20.4
    - ply >=3.11
    - pyparsing >=3.0.0
    - pyyaml >=5.4
    - requests >=2.25.1
    - scikit-build >=0.11.1
    - six >=1.14.0
    - sympy <=1.9
    - urllib3 >=1.26.5
    - websockets >=9.1
    - werkzeug >=2.2.3
    - dill
    - pyreadline  # [win]
    - dataclasses  # [py<37]
    - typing-compat  # [py<38]

test:
  imports:
    - dace
  commands:
    - sdfgcc --help
    - dacelab --help
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spcl/dace
  summary: Data-Centric Parallel Programming Framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tbennun
    - lukastruemper
